name: Reset Test

on: 
  pull_request:

jobs: 
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: remove file
        run: rm addition.py


